:rhid: how-to-read-poems
:type: concept
:used: emily-dickenson,robert-frost
:previous: 
:next:  

= How to read poems

== Read with a pencil

. Read a poem with a pencil in your hand.

. Mark it up; write in the margins; react to it; get involved with it. Circle important, or striking, or repeated words. Draw lines to connect related ideas. Mark difficult or confusing words, lines, and passages.

. Read through the poem several times, both silently and aloud, listening carefully to the sound and rhythm of the words.


== Examine the basic subject of the poem

. Consider the title of the poem carefully. What does it tell you about the poem's subject, tone, and genre? What does it promise? (After having read the poem, you will want to come back to the title in order to consider further its relationship with the poem.)

. What is your initial impression of the poem's subject? Try writing out an answer to the question, "What is this poem about?"--and then return to this question throughout your analysis. Push yourself to be precise; aim for more than just a vague impression of the poem. What is the author's attitude toward his or her subject?

. What is the poem's basic situation? What is going on in it? Who is talking? To whom? Under what circumstances? Where? About what? Why? Is a story being told? Is something--tangible or intangible--being described? What specifically can you point to in the poem to support your answers?

. Because a poem is highly compressed, it may help you to try to unfold it by paraphrasing the poem aloud, moving line by line through it. If the poem is written in sentences, can you figure out what the subject of each one is? The verb? The object of the verb? What a modifier refers to? Try to untie any syntactic knots.

. Is the poem built on a comparison or analogy? If so, how is the comparison appropriate? How are the two things alike? How different?

. What is the author's attitude toward his subject? Serious? Reverent? Ironic? Satiric? Ambivalent? Hostile? Humorous? Detached? Witty?

. Does the poem appeal to a reader's intellect? Emotions? Reason?

== Consider the context of the poem

. Are there any allusions to other literary or historical figures or events? How do these add to the poem? How are they appropriate?

. What do you know about this poet? About the age in which he or she wrote this poem? About other works by the same author? 

== Study the form of the poem

. Consider the sound and rhythm of the poem. Is there a metrical pattern? If so, how regular is it? Does the poet use rhyme? What do the meter and rhyme emphasize? Is there any alliteration? Assonance? Onomatopoeia? How do these relate to the poem's meaning? What effect do they create in the poem?

. Are there divisions within the poem? Marked by stanzas? By rhyme? By shifts in subject? By shifts in perspective? How do these parts relate to each other? How are they appropriate for this poem?

. How are the ideas in the poem ordered? Is there a progression of some sort? From simple to complex? From outer to inner? From past to present? From one place to another? Is there a climax of any sort?

. What are the form and genre of this poem? What should you expect from such a poem? How does the poet use the form?


== Look at the word choice of the poem

. One way to see the action in a poem is to list all its verbs. What do they tell you about the poem?

. Are there difficult or confusing words? Even if you are only the slightest bit unsure about the meaning of a word, look it up in a good dictionary. If you are reading poetry written before the twentieth century, learn to use the Oxford English Dictionary, which can tell you how a word's definition and usage have changed over time. Be sure that you determine how a word is being used--as a noun, verb, adjective, adverb--so that you can find its appropriate meaning. Be sure also to consider various possible meanings of a word and be alert to subtle differences between words. A good poet uses language very carefully; as a good reader you in turn must be equally sensitive to the implications of word choice.

. What mood is evoked in the poem? How is this accomplished? Consider the ways in which not only the meanings of words but also their sound and the poem's rhythms help to create its mood.

. Is the language in the poem abstract or concrete? How is this appropriate to the poem's subject?

. Are there any consistent patterns of words? For example, are there several references to flowers, or water, or politics, or religion in the poem? Look for groups of similar words.

. Does the poet use figurative language? Are there metaphors in the poem? Similes? Is there any personification? Consider the appropriateness of such comparisons. Try to see why the poet chose a particular metaphor as opposed to other possible ones. Is there a pattern of any sort to the metaphors? Is there any metonymy in the poem? Synechdoche? Hyperbole? Oxymoron? Paradox? A dictionary of literary terms may be helpful here.


== Finishing Up

Ask, finally, about the poem, "So what?" What does it do? What does it say? What is its purpose?
